### ISSUE TITLE
Migrations currently fail due to using SQLite

### ISSUE THREAD

**Issue by JasperGray** [bealsbe/Floofbot#13]
## The Problem

Run `dotnet ef migrations add RefreshFieldNames` and rebuild.
Upon running the bot, this exception occurs:

```
Unhandled exception. System.NotSupportedException: SQLite does not support this migration operation ('AlterColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.
   at Microsoft.EntityFrameworkCore.Migrations.SqliteMigrationsSqlGenerator.Generate(AlterColumnOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__71_4(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.SqliteMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Floofbot.Handlers.CommandHandler..ctor(DiscordSocketClient client) in /home/jasper/code/Floofbot/Floofbot/Handlers/CommandHandler.cs:line 25
   at Floofbot.Program.MainAsync(String token) in /home/jasper/code/Floofbot/Floofbot/Program.cs:line 87
   at Floofbot.Program.Main(String[] args) in /home/jasper/code/Floofbot/Floofbot/Program.cs:line 34
   at Floofbot.Program.<Main>(String[] args)
Aborted (core dumped)
```

## Potential Solutions

We can manually write out the migrations (see https://docs.microsoft.com/en-ca/ef/core/providers/sqlite/limitations#migrations-limitations-workaround).
Or, we use another DB such as MySQL. @jkchen2 is familiar with PostgreSQL but we haven't checked if it works with Entity Framework yet.

**Comment by jkchen2** [comment]
The general consensus is that we should be using MySQL. Although do note that this may hurt any cross-platform capabilities.

**Comment by bealsbe** [comment]
I am open to other suggestions as well

**Comment by JasperGray** [comment]
Well there's this https://www.mysql.com/support/supportedplatforms/database.html
MySQL 8.0 looks alright, unless someone here is on an old Debian or Solaris OS.

**Comment by JasperGray** [comment]
Closing the issue because a fix is as follows within the migration file:

- Create a new table with the desired schema
- Transfer over the data
- Drop the original table
- Rename the new table with the name of the original table

We'll have to do this for now until we switch to a DB like MySQL.
